[build-system]
requires = ["poetry-core>=1.1.0a7"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true

[tool.poetry]
name = "blab-chatbot-watson"
version = "0.0.1dev"
description = ""
authors = ["C4AI"]
readme = "README.md"

[tool.poetry.scripts]
c4aitm = 'blab_chatbot_watson:watson_assistant_bot.main'

[tool.poetry.dependencies]
python = "^3.10"
ibm-watson = "^6.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
darglint = "*"
flake8 = "*"
flake8-annotations = "*"
flake8-docstrings = "*"
flake8-bugbear = "*"
python-lsp-server = { extras = ["all"], version = "*" }
pyupgrade = "*"
mypy = "^0.931"
pre-commit = "^2.18.1"
black = "^22.3.0"



